### ISSUE TITLE
feature wish: show value change alternative to percent

### ISSUE THREAD

**Issue by peters77** [BT-OpenSource/bt-grafana-trend-box#4]
Hi,

I would like to show a trend of a temperature and checked your trend box. It's working fine. 

It would be nice if there could be an option to show the value change not in percent but with the used units!?

Regards,

Christian 

Example:

![bildschirmfoto 2017-10-23 um 23 58 26](https://user-images.githubusercontent.com/8840918/31915330-5d335fac-b84e-11e7-80be-f3e914439c8d.png)

**Comment by benthorner** [comment]
Hi Christian, thanks for the suggestion. This is something we could do, but it we wouldn't a simple switch as this doesn't scale well. Instead, we can look at exposing the calculations for the middle and bottom values (and their units), which is what we've done for some of our other plugins (https://github.com/BT-OpenSource/bt-grafana-alarm-box). Would that work for you?

**Comment by peters77** [comment]
Hi,

thank you for your answer and suggestion. 

I now used the single stat box and did a difference query. That works for me.

Regards,

Christian
![single stat trend](https://user-images.githubusercontent.com/8840918/31941707-09e9f4a8-b8c3-11e7-836b-245b0e83e82c.png)

**Comment by benthorner** [comment]
OK. Closing as nothing to do.
